Repository radepejanvic/PKI-server, pull requests merged in 2024-04, with the labels that each got.

#1 feat: Initialized Spring boot project
  pki-application/.gitignore
  pki-application/.mvn/wrapper/maven-wrapper.jar
  pki-application/.mvn/wrapper/maven-wrapper.properties
  pki-application/mvnw
  pki-application/mvnw.cmd
  pki-application/pom.xml
  pki-application/src/main/java/com/example/pki/pkiapplication/PkiApplication.java
  pki-application/src/main/resources/application.properties
  pki-application/src/test/java/com/example/pki/pkiapplication/PkiApplicationTests.java
Labels: enhancement

#2 Feat/auth
  pki-application/.gitignore
  pki-application/.mvn/wrapper/maven-wrapper.jar
  pki-application/.mvn/wrapper/maven-wrapper.properties
  pki-application/mvnw
  pki-application/mvnw.cmd
  pki-application/pom.xml
  pki-application/src/main/java/com/example/pki/pkiapplication/PkiApplication.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/WebConfig.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/WebSecurityConfiguration.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/jwt/JwtRequestFilter.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/jwt/JwtTokenUtil.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/AuthenticationController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/UserCredentialsDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/User.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/enums/UserType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/IUserRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/UserDetailsServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/validation/ValidationErrorsHandler.java
  pki-application/src/main/resources/application.properties
  pki-application/src/test/java/com/example/pki/pkiapplication/PkiApplicationTests.java
Labels: enhancement

#3 Infrastructure initialization
  pki-application/pom.xml
  pki-application/src/main/java/com/example/pki/pkiapplication/PkiApplication.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/WebConfig.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/WebSecurityConfiguration.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/jwt/JwtRequestFilter.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/jwt/JwtTokenUtil.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/AuthenticationController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/UserCredentialsDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSR.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Certificate.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CertificateStatus.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CertificateType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Extension.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/User.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/enums/UserType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/CSRRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/CertificateRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/UserRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CSRService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CertificateService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/JpaService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CSRServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/UserDetailsServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/validation/ValidationErrorsHandler.java
  pki-application/src/main/resources/application.properties
Labels: enhancement

#4 Feat/csr
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CSRController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CSRDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/mapper/CSRDTOMapper.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSR.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSRStatus.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Certificate.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CertificateType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Extension.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/CSRRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/CertificateRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/IUserRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/UserRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CSRService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CertificateService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/JpaService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CSRServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/UserDetailsServiceImpl.java
  pki-application/src/main/resources/application.properties
Labels: enhancement

#6 Implemented private key generating and storing mechanism
  pki-application/pom.xml
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/KeyPairController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CertificateService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/EncryptionService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/KeyStoringService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CRRServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CSRServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/PemKeyStoringService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/RSAEncryptionServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/utils/KeyGenerator.java
  pki-application/src/main/java/com/example/pki/pkiapplication/utils/RSAKeyGenerator.java
  pki-application/src/main/resources/application.properties
Labels: enhancement

#7 Feat/cert storing
  pki-application/pom.xml
  pki-application/src/main/java/com/example/pki/pkiapplication/PkiApplication.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/KeyPairController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/UserCredentialsDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSR.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CertificateType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Issuer.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CSRService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/CertificateGenerator.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyGenerator.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyStoreReader.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyStoreWriter.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/RSAKeyGenerator.java
  pki-application/src/main/resources/static/example.jks
Labels: enhancement

#8 fix: Add claims in jwt in login response
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/jwt/JwtTokenUtil.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/UserService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/UserServiceImpl.java
  pki-application/src/main/resources/static/example.jks
Labels: bug

#9 Initial certificate generating chain
  pki-application/src/main/java/com/example/pki/pkiapplication/PkiApplication.java
  pki-application/src/main/java/com/example/pki/pkiapplication/config/security/WebSecurityConfiguration.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CSRController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/KeyPairController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CRRDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CSRDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CertificateDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/mapper/CSRDTOMapper.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSR.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Certificate.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Issuer.java
  pki-application/src/main/java/com/example/pki/pkiapplication/repository/CertificateRepository.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CertificateService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateGeneratingServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/KeyStoringServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/PemKeyStoringService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/CertificateGenerator.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyDecoder.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyStoreReader.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyStoreWriter.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/PemKeyStore.java
  pki-application/src/main/resources/application.properties
Labels: enhancement

#11 Expanded certificate generating endpoints
  pki-application/src/main/java/com/example/pki/pkiapplication/PkiApplication.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CSRController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CSRDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CertificateDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/mapper/CertificateDTOMapper.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSR.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Certificate.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CertificateType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/enums/CSRStatus.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/enums/CertificateType.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateGeneratingServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/CertificateGenerator.java
  pki-application/src/main/resources/keys/CA za qwwweeep.pem
  pki-application/src/main/resources/keys/RootPROBA.pem
  pki-application/src/main/resources/keys/probaServisa.pem
  pki-application/src/main/resources/keys/qweqweqweq.pem
  pki-application/src/main/resources/keys/rade@gmail.com.pem
  pki-application/src/main/resources/keys/root@gmail.com.pem
  pki-application/src/main/resources/keys/uopa.pem
  pki-application/src/main/resources/static/example.jks
Labels: enhancement

#12 Feat/certificate controller
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CSRController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/resources/keys/BookingCA.pem
  pki-application/src/main/resources/keys/SAMO ZA DUKIJA.pem
  pki-application/src/main/resources/static/example.jks
Labels: enhancement

#13 Updated certificate DTO for front end preview
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CertificateDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/mapper/CertificateDTOMapper.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Certificate.java
  pki-application/src/main/resources/application.properties
  pki-application/src/main/resources/keys/ROOT.pem
  pki-application/src/main/resources/static/example.jks
  pki-application/src/main/resources/static/https.jks
Labels: enhancement

#14 Feat/cert extensions
  pki-application/src/main/java/com/example/pki/pkiapplication/dto/CSRDTO.java
  pki-application/src/main/java/com/example/pki/pkiapplication/mapper/CSRDTOMapper.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/CSR.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/Issuer.java
  pki-application/src/main/java/com/example/pki/pkiapplication/model/enums/KeyUsage.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateGeneratingServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/KeyStoringServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/CertificateGenerator.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/ExtensionsGenerator.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyStoreReader.java
Labels: enhancement

#16 Feat/validation
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/ValidatingService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/ValidatingServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/ExtensionsGenerator.java
  pki-application/src/main/resources/keys/BookingCA.pem
  pki-application/src/main/resources/keys/MaricTatko.pem
  pki-application/src/main/resources/keys/ROOT.pem
  pki-application/src/main/resources/static/example.jks
Labels: bug, enhancement

#18 Certificate and private key deletion
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/CertificateService.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/KeyStoringServiceImpl.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/KeyStoreDeleter.java
  pki-application/src/main/java/com/example/pki/pkiapplication/util/PemKeyStore.java
Labels: enhancement

#19 Feat/https
  pki-application/src/main/java/com/example/pki/pkiapplication/config/WebConfig.java
  pki-application/src/main/java/com/example/pki/pkiapplication/mapper/CertificateDTOMapper.java
  pki-application/src/main/java/com/example/pki/pkiapplication/service/impl/CertificateGeneratingServiceImpl.java
  pki-application/src/main/resources/application.properties
  pki-application/src/main/resources/keys/BookingCA.pem
  pki-application/src/main/resources/keys/CA za qwwweeep.pem
  pki-application/src/main/resources/keys/DuleCA.pem
  pki-application/src/main/resources/keys/IntermediaryCA.pem
  pki-application/src/main/resources/keys/MaricCA.pem
  pki-application/src/main/resources/keys/MaricTatko.pem
  pki-application/src/main/resources/keys/ROOT.pem
  pki-application/src/main/resources/keys/Rade.pem
  pki-application/src/main/resources/keys/RadeCA.pem
  pki-application/src/main/resources/keys/RootPROBA.pem
  pki-application/src/main/resources/keys/SAMO ZA DUKIJA.pem
  pki-application/src/main/resources/keys/asdasd@asda.sad.pem
  pki-application/src/main/resources/keys/booking@gmail.com.pem
  pki-application/src/main/resources/keys/dule@aws.com.pem
  pki-application/src/main/resources/keys/https@gmail.com.pem
  pki-application/src/main/resources/keys/probaServisa.pem
  pki-application/src/main/resources/keys/qweqweqweq.pem
  pki-application/src/main/resources/keys/rade@gmail.com.pem
  pki-application/src/main/resources/keys/rade@gmailc.om.pem
  pki-application/src/main/resources/keys/radefaks@gmail.com.pem
  pki-application/src/main/resources/keys/root@gmail.com.pem
  pki-application/src/main/resources/keys/uopa.pem
  pki-application/src/main/resources/keys/uros@aws.com.pem
  pki-application/src/main/resources/static/example.jks
Labels: bug

#20 fix: change status of csr after accepting
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/resources/keys/BookingCA.pem
  pki-application/src/main/resources/keys/qweqweqweq.pem
  pki-application/src/main/resources/static/example.jks
Labels: bug

#21 feat: add cross origin policy for https
  pki-application/src/main/java/com/example/pki/pkiapplication/config/WebConfig.java
  pki-application/src/main/java/com/example/pki/pkiapplication/controller/CertificateController.java
  pki-application/src/main/resources/static/example.jks
Labels: enhancement
